aa: "rand-m9-mstd0.5-inc1"
amp: true
attn_drop_rate: 0.0
batch_size: 128
checkpoint_hist: 3
clip_grad: 1.0
clip_mode: "norm"
color_jitter: 0.4
cooldown_epochs: 0
crop_pct: 0.9
cutmix: 1.0
dataset: ""
distill_weight: 0.0
drop_path_rate: 0.1
drop_rate: 0.0
dtem_eval_grouping: "alternating_per_layer_fast"
dtem_eval_grouping_seed: 0
dtem_feat_dim: 64
dtem_r: 2
dtem_spatial_backend: "sparse"
dtem_spatial_metric: "euclidean"
dtem_spatial_radius: 3.0
dtem_t: 1
dtem_train_grouping: "random_per_sample"
dtem_train_grouping_seed: 0
dtem_window_size: 0
epochs: 300
eval_metric: "top1"
feat_distill_token_weight: 0.0
feat_distill_weight: 0.0
find_unused_parameters: "false"
img_size: 224
lambda_local: 2.0
latent_depth: 6
local_block_window: 16
local_cls_global: true
local_depth: 6
log_interval: 50
lr: 0.00075
metric_grad_scale: 0.1
min_lr: 1.0e-05
mixup: 0.8
mixup_mode: "batch"
mixup_prob: 1.0
mixup_switch_prob: 0.5
model: "mergenet_small_cls"
model_ema: true
model_ema_decay: 0.99996
no_prefetcher: true
num_classes: 1000
opt: "adamw"
opt_eps: 1.0e-08
patch_size: 8
pin_mem: true
pretrained: false
recount: 1
recovery_interval: 1000
remode: "pixel"
reprob: 0.25
routing_distill_weight: 0.0
sched: "cosine"
seed: 42
smoothing: 0.1
soft_topk: true
soft_topk_aux_ramp_epochs: 20
soft_topk_aux_start_epoch: 20
soft_topk_aux_weight: 0.05
source_trace_mode: "center"
swa_size: 256
total_merge_latent: 0
train_interpolation: "bicubic"
train_split: "train"
update_freq: 1
use_softkmax: true
val_split: "val"
validation_batch_size: 64
warmup_epochs: 5
warmup_lr: 1.0e-06
weight_decay: 0.05
worker_seeding: "all"
workers: 8
